# Generated by Django 6.0.3 on 2026-03-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateEmployees',
            fields=[
                ('Name', models.CharField(max_length=1000)),
                ('Username', models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employees',
            name='EmployeeAge',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='EmployeeName',
        ),
    ]
